### PR TITLE
Add sudo required to .travis.yml

### PR DESCRIPTION
**Pull request by metaodi**

### CODE REVIEW

**Comment by metaodi** [comment]
The build on my fork works: https://travis-ci.org/ogdch/ckanext-scheming/jobs/95310037, so I guess this has something to do with coveralls.

**Comment by wardi** [comment]
I'm not sure what's happening here. I've disabled coverage for now

**Comment by metaodi** [comment]
ping @wardi

**Comment by wardi** [comment]
This change didn't fix coveralls for me when I tried it. Want to try re-enabling coveralls as part of this PR and see if it does now?

**Comment by metaodi** [comment]
@wardi this is a misunderstanding, this PR was not meant to fix the coveralls error, but to fix the travis build of my fork. But I'm happy to test, if I can help.

**Comment by wardi** [comment]
Oh, ok. so travis working on this repo because travis somehow remembers that it should use the legacy vm. Sure, I can merge this so that it works on forks as well.

**Pull request merged**
