### PR TITLE
#284 Now the add buttow will point to the right component even if we have …

### PR DESCRIPTION
**Pull request by ccancellieri**
I've ported the changes we made (on our customization) but I'm not able to test.
Also I see that it's a bit intrusive so feel free to evaluate this pull req only as an Idea.

### CODE REVIEW

**Comment by Conzar** [comment]
Greetings.  Thank you for this PR!  I am testing it on my local development.  Indeed, when adding fields, it works. However, the remove button no longer functions :(

**Comment by ccancellieri** [comment]
Sorry I forgot the last part, I also removed the hidden field.
Having an empty hidden field will push in the metadata an empty field when you click on save from the interface.
Actually this may resolve an alignment problem with rest uploaded metadata using api.

**Comment by ccancellieri** [comment]
> Greetings. Thank you for this PR! I am testing it on my local development. Indeed, when adding fields, it works. However, the remove button no longer functions :(

Thanks for testing, apologize for the missing piece (I'm manually porting changes, from our customized branch) hope this will address the task not causing side effects.

**Comment by Conzar** [comment]
Hello.  Thanks again.  I am still having an issue with the 'remove' button.

I did the following to apply the changes:

```bash
wget https://github.com/ckan/ckanext-scheming/pull/285.patch
git am 285.patch
```
The output was the following:
```bash
Applying: Now the add buttow will point to the right component even if we have multiple instances of multiple_text
Applying: missing remove field fix
```

**Comment by Patrick1Rhode** [comment]
Hi @ccancellieri ,

Looks interesting let me try to use it on my project.

**Comment by ccancellieri** [comment]
Thanks @Patrick1Rhode for your assistance, we tested and there were another mistake coming from the (-custom)ized js.
Now looks better @Patrick1Rhode will confirm after tests.

**Comment by Patrick1Rhode** [comment]
Good day @ccancellieri, 

I switched to your branch and everything works fine. Thank you!. 
test

**Comment by Conzar** [comment]
I have tested and both adding and removal buttons work.  The repeated fields get saved to the correct parent.  Thank you!

**Pull request merged**
