### PR TITLE
fix error text position for multiple_select.html

### PR DESCRIPTION
**Pull request by fanjinfei**

### CODE REVIEW

**Comment by fanjinfei** [comment]
ready for review

**Comment by thriuin** [comment]
@wardi Can you review, thanks

**Comment by wardi** [comment]
What's wrong with the error text position? Maybe this should be fixed in the macro instead.

**Comment by fanjinfei** [comment]
The problem is that the error message is put after the help_text (see internal issue 80). The macro input_block has nothing to fix.

**Comment by wardi** [comment]
but if you never pass errors to input_block won't the box be styled incorrectly when there are errors?

**Comment by fanjinfei** [comment]
The part of the multi-select and error inside multi-select.html will end up as {{ caller() }} at https://github.com/open-data/ckanext-wet-boew/blob/master/ckanext/wet_boew/templates/wet_boew/macros/form.html#L286 . It is still inside the input_block.

**Comment by fanjinfei** [comment]
internal issue 80

**Comment by wardi** [comment]
This repo is used outside our site so let's keep the discussion here. Would you look into the test failure and provide a screen shot of the before/after on a bare ckan instance (no wet or custom theme)?

**Comment by fanjinfei** [comment]
The test error is about `curl -fsSL https://raw.githubusercontent.com/michaelcontento/circleci-matrix/master/src/circleci-matrix.sh`. I am not sure what does that mean. For the bare ckan test, what is proper setup so it can use this repo? Any tutor link?

**Comment by wardi** [comment]
@fanjinfei would you merge from master? the tests should be fixed now

**Comment by fanjinfei** [comment]
@wardi still tests failed.

**Comment by wardi** [comment]
you need to fetch and merge from master or rebase again. (your remote is probably be out of date)

**Pull request merged**
