### PR TITLE
add is_required to upload.html

### PR DESCRIPTION
**Pull request by fanjinfei**

### CODE REVIEW

**Comment by fanjinfei** [comment]
@wardi So we need to fix form.html in ckan to pass the test here?

**Comment by wardi** [comment]
this just says that the core image_upload macro doesn't have the new parameter you've added. Maybe the default styling of scheming on vanilla ckan makes the URL and image upload sections of the form look like they are required somehow

**Comment by fanjinfei** [comment]
@wardi It seems vanilla ckan need to be fixed. I can not find the styling about 'required'.

**Comment by wardi** [comment]
Ok, I'll close this then

**Pull request closed without merging**
