### PR TITLE
Upgrade pytz to match ckan 2.6

### PR DESCRIPTION
**Pull request by Zharktas**
CKAN core upgraded pytz and install will complain about version conflict.

### CODE REVIEW

**Comment by wardi** [comment]
the circleci failures look unrelated. Looks like we're using the wrong version of the schema for testing against older CKANs. I'll take a look at that.

Regarding your change, I think we should make the pytz requirement looser because this extension supports a range of CKAN versions, not just the latest one.

**Comment by Zharktas** [comment]
Apparently since older pytz does not use semantic versioning, it is not possible to specify version ranges. Only option would be specifying just pytz as a requirements

**Comment by coreyerickson** [comment]
I also was encountering this issue deploying scheming with ckan 2.6.0 until removing the pytz version from the requirements file. 

If you installed the scheming requirements to your virtualenv after installing the ckan requirements you will get version conflict.

pytz

**Comment by wardi** [comment]
fixed by #145

**Pull request closed without merging**
