### PR TITLE
Simple template updates to support 'default' values in schemas.

### PR DESCRIPTION
**Pull request by TkTech**

### CODE REVIEW

**Comment by wardi** [comment]
The c.action test doesn't work for new resources, right?

**Comment by wardi** [comment]
@TkTech could you add some defaults to the camel-photos schema and a couple simple tests to https://github.com/open-data/ckanext-scheming/blob/master/ckanext/scheming/tests/test_form.py#L34 that show the defaults appearing in datasets and resources? (if the resources aren't working use SkipTest for now)

**Comment by wardi** [comment]
@TkTech so there's no way to make this approach work with resources without a core ckan change? I might just switch this to testing for the presence of the fields in the data passed, unless you already know that doesn't work

**Comment by TkTech** [comment]
@wardi Yes, we can make it work with resources, I just haven't had time to do it yet.

**Comment by wardi** [comment]
ok, thanks

**Comment by wardi** [comment]
Just needs a description of the feature in the README and small tests in https://github.com/open-data/ckanext-scheming/blob/master/ckanext/scheming/tests/test_form.py that defaults appear and don't overwrite existing values in the dataset and resource forms

**Comment by TkTech** [comment]
Better ways to do this I think and we no longer need it for NDM.

**Pull request closed without merging**
